# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Limentum Projects
email: contact@limentum.com
description: A collection of projects by Limentum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://projects.limentum.com" # the base hostname & protocol for your site, e.g. http://example.com
website: "https://limentum.com"
collections:
  vestige:
    output: true
    permalink: /vestige/:title

plugins:
  - jekyll-seo-tag
  - base64

kramdown:
  input: GFM
  auto_ids: true
  footnote_backlink: ↩
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

jekyll-seo-tag:
  robots: "index, follow"
  title_separator: "-"
  title: "Limentum Projects"
  description: "A collection of projects by Limentum."
  image: "/assets/images/logo512.png"
  canonical_url: "https://projects.limentum.com"

exclude:
  - readme.md
  - CNAME
  - /_drafts