# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Limentum Projects
email: contact@limentum.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of projects by Limentum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://projects.limentum.com" # the base hostname & protocol for your site, e.g. http://example.com
website: "https://limentum.com"
github_username:  limentum
threads_username: limentum
linktree_username: limentum
instagram_username: limentum
youtube_username: limentum
logo: /_themes/theme/assets/images/logo512.png
collections:
  vestige:
    output: true
    permalink: /vestige/:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

jekyll-feed:
  posts:
    limit: 10
  collections:
    vestige:
      output: true
      limit: 10
  rss_path: rss.xml
  atom_path: feed.xml
  json_path: feed.json

jekyll-sitemap:
  defaults:
    sitemap: true

jekyll-minifier:
  remove_spaces_inside_tags: true   # Remove spaces inside HTML tags
  js_minify: true                   # Minify JavaScript
  css_minify: true                  # Minify CSS
  tidy_html: true                   # Tidy (prettify) HTML
  remove_multi_spaces: true         # Remove multiple consecutive spaces
  remove_comments: true             # Remove HTML comments
  remove_intertag_spaces: true      # Remove inter-tag spaces
  remove_quotes: true               # Remove quotes from tag attributes
  remove_script_attributes: true    # Remove type="text/javascript" from script tags
  remove_style_attributes: true     # Remove type="text/css" from style tags
  remove_link_attributes: true      # Remove type="text/css" from link tags

jekyll-seo-tag:
  robots: "noindex, nofollow"
  title_separator: "-"
  title: "Limentum Projects"
  description: "A collection of projects by Limentum."
  image: "/assets/images/logo512.png"
  canonical_url: "https://projects.limentum.com"

exclude:
  - readme.md